### ISSUE TITLE
DataSource Switch 无法使用druid

### ISSUE THREAD

**Issue by Tarems** [minbox-projects/api-boot#51]
apiboot版本: 2.3.0
只使用ApiBoot DataSource Switch
使用druid后发现数据源还是HikariCP
```api:
  boot:
    datasource:
      primary: lzj
      druid:
```
程序运行时显示
2020-08-05 10:54:04 [http-nio-80-exec-3] [INFO ] com.zaxxer.hikari.HikariDataSource -HikariPool-1 - Starting...

**Comment by hengboy** [comment]
@Tarems 请把详细的`application.yml`相关配置贴出来吧

**Comment by Tarems** [comment]
> @Tarems |`application.yml`

```
api:
  boot:
    datasource:
      primary: lzj
      druid:
        lzj:
          url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=net)))
          username: xxxxx
          password: xxxxx
          driver-class-name: oracle.jdbc.OracleDriver
```
