### ISSUE TITLE
api-boot-starter-logging 导致druid 监控界面无法登陆，提示用户名密码错误

### ISSUE THREAD

**Issue by randeexiong** [minbox-projects/api-boot#85]
当引用 logging日志组件，druid监控将无法正常登陆，提示用户名密码错误

但是目前使用的可配置的参数都无法避免错误问题，请求指导
```xml
        <dependency>
            <groupId>org.minbox.framework</groupId>
            <artifactId>api-boot-starter-logging</artifactId>
        </dependency>
```

**Comment by hengboy** [comment]
被`org.minbox.framework.logging.client.filter.LoggingBodyFilter`过滤器拦截后就出现了你所描述的问题

**Comment by randeexiong** [comment]
> 被`org.minbox.framework.logging.client.filter.LoggingBodyFilter`过滤器拦截后就出现了你所描述的问题

现在LoggingBodyFilter默认过滤所有请求，在目前发布的版本上有什么方法可以放行指定的请求吗？

**Comment by hengboy** [comment]
参考`org.minbox.framework.api.boot.autoconfigure.logging.ApiBootLoggingProperties`配置类的属性

**Comment by randeexiong** [comment]
尝试使用了ignorePaths，问题还是存在

**Comment by hengboy** [comment]
怎么排除的？druid的管理端应该是有地址前缀，比如你可以排除：/druid/**

**Comment by randeexiong** [comment]
> 怎么排除的？druid的管理端应该是有地址前缀，比如你可以排除：/druid/**

是这样写的

**Comment by randeexiong** [comment]
> 怎么排除的？druid的管理端应该是有地址前缀，比如你可以排除：/druid/**

```yml
api:
  boot:
    # ApiBoot Logging相关配置
    logging:
      format-console-log-json: true
      show-console-log: true
      # 配置日志排除的采集的接口地址列表
      ignore-paths:
        - /swagger-resources/**
        - /swagger-ui.html
        - /webjars/**
        - /druid/**
 ```
